# Generated by Django 3.1.2 on 2020-10-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructeurVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamillePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarquePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('motorisation', models.CharField(blank=True, choices=[('e', 'Essence'), ('d', 'Diesel')], max_length=1, null=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.constructeurvoiture')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.famillepiece')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.marquepiece')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.voiture')),
            ],
        ),
    ]
