# Generated by Django 3.1.2 on 2020-11-09 22:02

import app_parts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructeurVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FamillePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarquePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('motorisation', models.CharField(blank=True, choices=[('e', 'Essence'), ('d', 'Diesel')], max_length=1, null=True)),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.constructeurvoiture')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, default=app_parts.models.increment_profile_id_number, max_length=1000, null=True)),
                ('organisation', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('adresse', models.CharField(blank=True, max_length=300, null=True)),
                ('photo_de_profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_client', models.BooleanField(default=False)),
                ('is_vendeur', models.BooleanField(default=False)),
                ('raison_social', models.CharField(blank=True, max_length=33, null=True)),
                ('adresse_siege', models.CharField(blank=True, max_length=400, null=True)),
                ('nif', models.CharField(blank=True, max_length=30, null=True)),
                ('nis', models.CharField(blank=True, max_length=30, null=True)),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('note', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.famillepiece')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.marquepiece')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_parts.voiture')),
            ],
        ),
    ]
