# Generated by Django 3.1.2 on 2020-11-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='owner',
            new_name='user',
        ),
    ]
