# Generated by Django 3.1.2 on 2020-11-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('adresse', models.CharField(blank=True, max_length=300, null=True)),
                ('photo_de_profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_client', models.BooleanField(default=False)),
                ('is_vendeur', models.BooleanField(default=False)),
                ('raison_social', models.CharField(blank=True, max_length=33, null=True)),
                ('adresse_siege', models.CharField(blank=True, max_length=400, null=True)),
                ('nif', models.CharField(blank=True, max_length=30, null=True)),
                ('nis', models.CharField(blank=True, max_length=30, null=True)),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('note', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
