# Generated by Django 3.1.2 on 2020-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructeurvoiture',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='piece',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
