# Generated by Django 3.1.2 on 2020-11-14 13:05

import app_parts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_parts', '0003_auto_20201114_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bon', models.CharField(blank=True, default=app_parts.models.increment_bon_id_number, max_length=1000, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('taux', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_parts.piece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
