# Generated by Django 3.1.2 on 2020-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parts', '0003_auto_20201101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='num_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
