# Generated by Django 3.1.2 on 2020-11-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parts', '0004_bonreduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
